---
# Docker User
dockerUser: geoffh1977
dockerUserEmail: geoffh1977@gmail.com
license: gnu-gpl-v3.0

# Source Build Variables
buildImageName: elasticsearch
buildImageVersion: latest

# Final Image Variables
finalImageName: elasticsearch-k8s
finalImageVersion: latest

appName: Elasticsearch Kubernetes
